# Generated by Django 4.1.3 on 2022-12-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_article_options_article_mdate_article_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
