# Generated by Django 4.1.3 on 2022-12-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
