# Generated by Django 4.1.3 on 2022-12-02 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-mdate',), 'verbose_name_plural': '아티클 작성하기'},
        ),
    ]
